### ISSUE TITLE
Create Your Developer Key Not Working

### ISSUE THREAD

**Issue by TimSnaith** [OnePointGlobal/OnePoint-API-Documentation-V2#2]
The 'Create Your Developer Key' is not working in the https://diysms.onepointglobal.com/home portal
Please see screenshot below and update asap please
![image](https://user-images.githubusercontent.com/26327747/121225979-f6177180-c881-11eb-8638-e175f63f6f09.png)

**Comment by hitesh-opg** [comment]
Keys are now being successfully created.
